### ISSUE TITLE
Fix font rendering for anchors

### ISSUE THREAD

**Issue by raaffaaeell** [acidiney/dev.acidineydias#5]
Currently, your anchors on the home page doesnt look too good (my resolution is 1920x1080)

![image](https://user-images.githubusercontent.com/6959662/89725977-a8bd4000-d9e3-11ea-966e-e10316b93045.png)

See the screenshot for reference.

**Comment by acidiney** [comment]
I don't know if it is a really screen resolution, I use the same resolution in my pc and looks good. 

I will try to explore the website to see If I can reproduce the same issue.

**Comment by raaffaaeell** [comment]
https://user-images.githubusercontent.com/6959662/89790448-f1fab600-daef-11ea-9161-02df1804d235.png

While hovering the text, it'll show it much better

https://user-images.githubusercontent.com/6959662/89790587-24a4ae80-daf0-11ea-873d-be257176da39.png

Forgot to mention, but I'm using latest Firefox on Windows 10

**Comment by acidiney** [comment]
![imagem](https://user-images.githubusercontent.com/24493328/89957189-b1558680-dc2e-11ea-93eb-61631832c1ae.png)

I don't know if this issue only occurs on windows, I use Linux and Firefox too... I have traid in other browers and linux pcs and looks good... maybe I need to check on windows ... Or change the font only

**Comment by acidiney** [comment]
#6
